name: "Run unit tests"
on: ["push"]
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test